### PR TITLE
 Add proper storybook controls

### PR DESCRIPTION
**Pull request by RoshanShrestha123**
# Motivation

This changes are made just on the storybook rather than component itself, which allows the user
to change the value in storybook via input field.

Fixes # ([Issue-43](https://github.com/Hexastack/eazychart/issues/35))

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have done the work for both react and vue
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (Storybook)
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Screenshot
### After
Screen Shot 2022-10-11 at 5 12 48 PM

### Before
Screen Shot 2022-10-11 at 5 14 09 PM

### CODE REVIEW

**Comment by marrouchi** [comment]
@RoshanShrestha123 Awesome draft :rocket ! I think it makes sense to leave the "data" as it was, a JSON input field.

I have a question, can we group a set of fields inside an fieldset element ?

**Comment by RoshanShrestha123** [comment]
> @RoshanShrestha123 Awesome draft :rocket ! I think it makes sense to leave the "data" as it was, a JSON input field.
> 
> I have a question, can we group a set of fields inside an fieldset element ?

I did some research, but couldn't find the way to group the fields. 
Again, do let me know if you have any idea, happy to implement.

Meanwhile i will refactor the code and implement the remaining code.

**Comment by marrouchi** [comment]
@RoshanShrestha123 Sounds good ! I'm eager to see the end result :smile:

**Comment by marrouchi** [comment]
@RoshanShrestha123 Any update on this ?

**Comment by marrouchi** [comment]
This PR will be closed in favor of the new one : https://github.com/Hexastack/eazychart/pull/93

Thank you @RoshanShrestha123 for this initial bootstrap :)

**Pull request closed without merging**
