### PR TITLE
fix: radialchart sorted data

### LINKED ISSUE #14: :bug: [BUG] - @eazychart-react - Data does not get sorted in RadialChart
### Description
`RadialChart` is not behaving correctly. The outer circular bar (arc) should display the max value of the data and therefore the bigger arc. This could be resulted from the `sortValue` function that is not working accordingly. The radial chart is a chart that has circular arcs that are displaying values from a giving column of data. 

### Reproduction steps
1. Create a React project
2. Install the eazychart-react and the eazychart-css packages.
```bash
npm install eazychart-react  eazychart-css
```
3. Add the radial chart to your app component
### Code
```typescript
import { RadialChart } from 'eazychart-react';
import 'eazychart-css';
const App = () => {
  return (
    <div className="App">
      <RadialChart
        colors={['#FF595E', '#FFCA3A', '#8AC926', '#1982C4', '#6A4C93']}
        arc={{ spacing: 0.3 }}
        domainKey={'value'}
        rawData={[
          { label: 'Alpha', value: 30 },
          { label: 'Gamma', value: 20 },
          { label: 'Beta', value: 10 },
          { label: 'Teta', value: 40 },
          { label: 'Zeta', value: 50 },
        ]}
      />
    </div>
  );
};

export default App;

```
### Screenshots 
image

### PR DESCRIPTION
**Pull request by yassinedorbozgithub**
# Motivation
RadialChart is not behaving correctly. The outer circular bar (arc) should display the max value of the data and therefore the bigger arc. This could be resulted from the sortValue function that is not working accordingly. The radial chart is a chart that has circular arcs that are displaying values from a giving column of data. (Description from the issue)
This PR fixes this issue.

Fixes #14 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have done the work for both react and vue
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (Storybook)
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by IlyesBenAmara** [comment]
:man_technologist:

**Review by IlyesBenAmara — APPROVED** [review]

**Review by marrouchi — CHANGES_REQUESTED** [review]
I suggest that we provide the sort function in the default "arc" prop value :
```
arc = {
    cornerRadius: 0,
    stroke: '#FFF',
    strokeWidth: 0,
    spacing: 0,
    sortValues: (a, b) => b - a
  },
```

**Comment by yassinedorbozgithub** [comment]
Hey @marrouchi 
The sortValues function will be applied only if arc is not undefined and by default arc have `{spacing: 0.5}` from the storybook.
I removed the arc value from the storybook and arc is now **null** and not **undefined**.
I think this means that the default **arc** prop config value will never be applied in this case.
Maybe if we created a default config variable named **arcDefaultConfig** and merge it with the **arc** prop giving priority to the passed **arc**.

**Comment by yassinedorbozgithub** [comment]
Hey @marrouchi the required updates for this PR are applied :
- :heavy_check_mark: Update **snapshot** file for **RadialChart**.
- :heavy_check_mark: Update the snapshot **arc** value to be **undefined**.
- :heavy_check_mark: Add the **sortValues** function to be part of RadialChart arc default config value gives the sort feature by default.
- :heavy_check_mark: Check the update compatibility with **React** and **Vue**

**Review by marrouchi — APPROVED** [review]
Looks awesome ! :rocket:

**Pull request merged**
